### PR TITLE
Norwegian Translation

### PR DESCRIPTION
**Pull request by HelgeSverre**
I have translated GS-Blog to Norwegian Bokmål.

If possible i would like to be credited on the website with a link to my website: https://helgesverre.com 
:)

### CODE REVIEW

**Comment by HelgeSverre** [comment]
Thanks for accepting the PR :)

**Comment by johnstray** [comment]
Thank-you for the translation. You will be credited on the website for the plugin.

**Comment by HelgeSverre** [comment]
You're welcome and thanks!
I'll keep the translation updated and fix any issues if I come across any.

**Comment by johnstray** [comment]
The next update to be released will be the last. I'm working on creating a new Blog plugin with an all new codebase. This plugin will takeover and replace the current one. https://github.com/johnstray/gs-simpleblog/

**Comment by johnstray** [comment]
Would you like to be a part of the team on the new plugin?

**Comment by HelgeSverre** [comment]
That would be an interesting learning experience, I am very new to plugin
development.
But I can give it a shot :)
I can also take care of translations in the new plugin.

On ons., jun. 24, 2015 at 4:15 p.m., John Stray < notifications@github.com [notifications@github.com] > wrote:
Would you like to be a part of the team on the new plugin?

—
Reply to this email directly or view it on GitHub
[https://github.com/johnstray/gs-blog/pull/72#issuecomment-114882420] .[https://github.com/notifications/beacon/ABCgdKKDswd_sMP14MSaT118zPdmFLkAks5oWrL5gaJpZM4FK1xP.gif]

**Comment by johnstray** [comment]
It's the translation part that I would like you to join the team for.

**Comment by HelgeSverre** [comment]
In that case, I'm on board :)

On ons., jun. 24, 2015 at 4:31 p.m., John Stray < notifications@github.com [notifications@github.com] > wrote:
It's the translation part that I would like you to join the team for.

—
Reply to this email directly or view it on GitHub
[https://github.com/johnstray/gs-blog/pull/72#issuecomment-114888671] .[https://github.com/notifications/beacon/ABCgdBej2Sbep1ns1smPpk6ef3UOsIF-ks5oWrbCgaJpZM4FK1xP.gif]

**Comment by johnstray** [comment]
Cheers, I'll add you to the repo now.

**Pull request merged**
